"""
Object state constants.

This module defines constants used in object state handling.
"""

from perception_msgs.msg import EGO, EGORWS, ISCACTR, HEXAMOTION, TRAFFICLIGHT
import sys

# Model IDs
EGO_MODEL_ID = EGO.MODEL_ID
EGORWS_MODEL_ID = EGORWS.MODEL_ID
ISCACTR_MODEL_ID = ISCACTR.MODEL_ID
HEXAMOTION_MODEL_ID = HEXAMOTION.MODEL_ID
TRAFFICLIGHT_MODEL_ID = TRAFFICLIGHT.MODEL_ID

# State sizes for each model
EGO_CONTINUOUS_STATE_SIZE = EGO.CONTINUOUS_STATE_SIZE
EGO_DISCRETE_STATE_SIZE = EGO.DISCRETE_STATE_SIZE
EGORWS_CONTINUOUS_STATE_SIZE = EGORWS.CONTINUOUS_STATE_SIZE
EGORWS_DISCRETE_STATE_SIZE = EGORWS.DISCRETE_STATE_SIZE
ISCACTR_CONTINUOUS_STATE_SIZE = ISCACTR.CONTINUOUS_STATE_SIZE
ISCACTR_DISCRETE_STATE_SIZE = ISCACTR.DISCRETE_STATE_SIZE
HEXAMOTION_CONTINUOUS_STATE_SIZE = HEXAMOTION.CONTINUOUS_STATE_SIZE
HEXAMOTION_DISCRETE_STATE_SIZE = HEXAMOTION.DISCRETE_STATE_SIZE
TRAFFICLIGHT_CONTINUOUS_STATE_SIZE = TRAFFICLIGHT.CONTINUOUS_STATE_SIZE
TRAFFICLIGHT_DISCRETE_STATE_SIZE = TRAFFICLIGHT.DISCRETE_STATE_SIZE

# State initialization values
CONTINUOUS_STATE_INIT = 0.0
DISCRETE_STATE_INIT = 0
CONTINUOUS_STATE_COVARIANCE_INIT = 0.0
CONTINUOUS_STATE_COVARIANCE_INVALID = -1.0
CONTINUOUS_STATE_COVARIANCE_UNKNOWN = sys.float_info.max 