uint8 MODEL_ID = 20
uint8 CONTINUOUS_STATE_SIZE = 3
uint8 DISCRETE_STATE_SIZE = 2

# continuous state
uint8 X = 0
uint8 Y = 1
uint8 Z = 2

# discrete state
uint8 STATE = 0
uint8 TYPE = 1

# discrete state enums
uint8 STATE_UNKNOWN = 0
uint8 STATE_RED = 1
uint8 STATE_RED_YELLOW = 2
uint8 STATE_YELLOW = 3
uint8 STATE_GREEN = 4
uint8 STATE_OFF = 255

uint8 TYPE_DEFAULT = 0
uint8 TYPE_STRAIGHT = 1
uint8 TYPE_LEFT = 2
uint8 TYPE_RIGHT = 3
uint8 TYPE_UNKNOWN = 255
